import {
    ArrowLeft,
    ArrowRight,
    BadgeCheck,
    Check,
    CheckCircle2,
    Compass,
    Eye,
    EyeOff,
    Home,
    Layers,
    Lock,
    Mail,
    Menu,
    Moon,
    PlusCircle,
    Search,
    SearchX,
    Send,
    ServerCrash,
    ShieldCheck,
    ShoppingBag,
    Sparkles,
    Star,
    Sun,
    User,
    X,
    Zap,
} from 'lucide-react';
import type { IconComponent } from './types.ts';

/**
 * Mapping of semantic icon names to Lucide React components.
 * This is the ONLY file in the entire application that imports from lucide-react.
 */
export const lucideRegistry = {
    Brand: ShoppingBag as IconComponent,
    Cart: ShoppingBag as IconComponent,
    Explore: Compass as IconComponent,
    Categories: Layers as IconComponent,
    Sell: PlusCircle as IconComponent,
    Search: Search as IconComponent,
    Menu: Menu as IconComponent,
    Close: X as IconComponent,
    ThemeLight: Sun as IconComponent,
    ThemeDark: Moon as IconComponent,
    Magic: Sparkles as IconComponent,
    Next: ArrowRight as IconComponent,
    Back: ArrowLeft as IconComponent,
    Home: Home as IconComponent,
    Send: Send as IconComponent,
    Success: CheckCircle2 as IconComponent,
    Security: ShieldCheck as IconComponent,
    Performance: Zap as IconComponent,
    Rating: Star as IconComponent,
    Verified: BadgeCheck as IconComponent,
    ServerError: ServerCrash as IconComponent,
    NoResults: SearchX as IconComponent,
    Check: Check as IconComponent,
    Eye: Eye as IconComponent,
    EyeOff: EyeOff as IconComponent,
    Lock: Lock as IconComponent,
    Mail: Mail as IconComponent,
    User: User as IconComponent,
} as const satisfies Record<string, IconComponent>;
